# Generated by Django 5.0.8 on 2024-09-15 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0004_userprofile_date_of_birth_userprofile_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2024, 9, 15)),
            preserve_default=False,
        ),
    ]
