# Generated by Django 5.0.8 on 2024-09-16 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0008_rename_question_text_testquestion_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='career_path',
        ),
        migrations.RemoveField(
            model_name='role',
            name='prerequisites',
        ),
        migrations.DeleteModel(
            name='CareerPath',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
