# Generated by Django 5.0.8 on 2024-09-16 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0009_remove_role_career_path_remove_role_prerequisites_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertestresponse',
            name='question',
        ),
        migrations.RemoveField(
            model_name='usertestresponse',
            name='user',
        ),
        migrations.DeleteModel(
            name='TestQuestion',
        ),
        migrations.DeleteModel(
            name='UserTestResponse',
        ),
    ]
