# Generated by Django 5.0.8 on 2024-09-16 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0010_remove_usertestresponse_question_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
