# Generated by Django 5.0.8 on 2024-09-16 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_careerpath'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('career_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.careerpath')),
                ('prerequisites', models.ManyToManyField(blank=True, to='accounts.role')),
            ],
        ),
    ]
