# Generated by Django 5.0.8 on 2024-12-07 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('question_type', models.CharField(choices=[('choice', 'Choice'), ('text', 'Text')], max_length=10)),
                ('options', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
